from src.entities.usuario import Usuario
from src.entities.departamento import Departamento
from src.entities.profesor import Profesor
from src.entities.grado import Grado
from src.entities.estudiante import Estudiante
from src.entities.curso import Curso
from src.entities.aula import Aula
from src.entities.calificacion import Calificacion
from src.entities.asistencia import Asistencia
from src.entities.horario import Horario
from src.entities.director import Director